sudo: false

dist: xenial

os: linux

language: python
python: 3.6


env:
  global:
    # Doctr deploy key for pyvista/website
    - secure: "ANzZOajPiDpCGihdLQEXQajwf2Z8j3iBp1ux0v5WwDPqWphC8svkzINTYQK0OSnrgz9uH99bxR6g9fLM/ebakJqWPISSf05HSN9vUAvj06zE+I4ILzKmzAj7ZcQnyfGzDioAmLDaUuGnK7Mui2BYKEFhScanvl101I66XYZ2lmyjfPVowov1FOoyEJtqfa7pgHYFm6vBeVaMY/8K/C3V2xQDaTrrEPb8TYdRCcvBRs/2iA7ubVzc7I7gd+/mQ3rDmePPGqk1Ndw05nSgp3dbrUqsBWTMhKSTgEkS6YviUCrOnpMHmwdxirwPXZ0p9n5xdl6B579ZDw5mkF3SgrLfbNwJ0av0pqatOlWjyq9B9uinfdoB4RiQT8RS/JntvpjcPT20/gQhbVLFGZMz3EDRaPUyQykgm4Toew5mD6FzAz0l8lciPT6AYpLlpccVaIXKOLRzRXQcrrRG38A96Fsw/iyw3JjHbMLJQR6AlQ1DsH2tHjW/HQ6+gKwvGtJGYd1khZOJJKbSew9sKRSyH/09WVN2vq96bkWlhjljOww4F2WUK9EdKKrl44TN8GiH4TEzL0eRIT8jq+wobyMNLs2aS0v8jbgApgYanXd8d2iM1qUtHHJlU34ojTSQV0sITemvASaxYCfusQPFPgeEx/GozCX7fRy4dA6zC6j+4MEHAjg="


install:
  - pip install -r requirements.txt


script:
  - make html


# Deploy the built HTML to Github pages
deploy:
    - provider: script
      script: doctr deploy . --built-docs _build/html --key-path ./github_deploy_key_pyvista_website.enc
      skip_cleanup: true
      on:
          branch: master


notifications:
  email: false
