sudo: false

dist: xenial

os: linux

language: python
python: 3.6


env:
  global:
    # Doctr deploy key for pyvista/website
    - secure: "xMD0JHtS5ufcW5LvIRFKDywcB1Mm3uFz9Z84xzv4VkUC3/cOHhxLHlLRpsWZHE1XfCN0pfHhQdeNpJMhs0dO/P+JZxzPH8k5S6Agi1iJMgsK7n4ZUMq/d2Qa1RxvTJE33/Yfw5a+QS9amMbViuQBuxpL0Id6WBTNGbpzgRcom+SMf9xcZAf+VJER7PKdT/xPnZnVOQXO0uV/2+8CsP9LO0r5dbk4SX/ofFuHeCqjG3mhcdztcZCWBFQ3EbJDSMpQk2M2WoRCCAY5VgO2z/U9qeTSi7/W5r1nhsF/DZQiQvZoKJnR6i/9ZecDdg0ISwaprpOUhyYcVUYispdFJtN1Gj5gKuc92akpEEmUmowNqKId6F6FVi0a5xWfgQvmhf76/LVMY8D7+lKKcs01OpZyjtyQGnvxdeLVC1YexlPL4pEzZt1tuCWIHb4FAndd8KRMWUWw6oA6nXx7kgSlzAqnQUX0K78ux3l8CZurTjku57F60ZEMAGtRi75vhcq3aPzBJKJALCGVLDE2xqG46Tyesn2AO0F3wMN6/rIrjRJwDkyq9r3ge5MCeJjIlsOem7m8Hfz+UbZfx/1R60hKTSTPXxd51XuE/I/7QE8fbwaFDEJ/wjEwY9PgHXFF4zXfzwO93ihFcoqh5egNnOTNsdVQb0IW6wGqL1KvnwVIIdohMRk="


install:
  - pip install -r requirements.txt


script:
  - make html


# Deploy the built HTML to Github pages
deploy:
    - provider: script
      script: doctr deploy . --built-docs _build/html --key-path ./github_deploy_key_pyvista_website.enc
      skip_cleanup: true
      on:
          branch: master


notifications:
  email: false
