sudo: required

dist: xenial

os:
  - linux

language: python
python: 3.7


env:
  global:
    # Doctr deploy key for pyvista/website
    - secure: "Jp/dgnu9B/9X0PdJ2fl0d4VCOPVjU+wdAxJJQEqoqo21xkb7QqCD3sQRJju/8WclC9j++VvFIagit9leJF3Xtmxu1LuDSwMC0EZb0kfG/eNEugpehpZNk+e0V+kr/Iq/KlmoXlf/JxXTW4pFuxA6f7iU+FvqFv3OfKsUQHFYjrlcno4pZKlCgCdW9crqx8ptmTbPznFSDgoyN/T+KXgl3V0DVuLej2PBLVQceacN9BkMQoSKIW4NuoJrNwvm1fXCJXLRHF+M5xJWEH48O8XrCrVk7ucCVgMXWBIcjCtxBjxqsSjmPyjpV2zOIPzT0X/lSvNezG+yp6eafmy40NiFuQMoYtbhcE/bllMYoFc3ax6zFJ8vJocj0kJARn9wmxICfaktod6xcwHfbCoyWigeeIlA5af5qPug/Xti2haixEWMqgdeqTqqXWUeUwNlSvke0sDMtUZaCTxSKQ7/06IKFg55O1WLTd8pKQ8i/s3N2Dhd40Y2kUbX1prQWmQ9mXdEtnrX5ShgDdg4GzDhD6EO0ofXU9CVlYHI0ERQ41bX920GZ2uHO3gXXbLug+yCbIjB/XbeVM9JteH8wbkscK8BtvzRjK9jngvmC5L9Z5kXEqwgxobYryDQ5zWjYI3Uv5riifGXqpWGAOr85BbSVhtIRfN2ONgJvnTCXfTFMsEXgRA="


install:
  - pip install -r requirements.txt


script:
  - set -e
  - make html
  - doctr deploy --built-docs ./_build/html/ .


notifications:
  email: false
